# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ca13defed66e3c4dbe713804918b99085626a12adf9089f3469db8302107145801c90053a5ef2f1e4d40b6754b1decbbb92408825a83583d3ce81a2b006bdb66

test:
  secret_key_base: 6ead7426f6d12ddbb9760fb1b2e433dd4bbf3b2b541cbdf313daeb15f2080014fce0cac668fcdaaec2d3349544099f1d67e0fdeba9778a9b8b2a9b6c2eb15074

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
